main: ${project.mainClass}

name: ${project.name}
version: '${project.version}'

description: "${project.description}"

author: ${project.author}
depend: [ProtocolLib]

permissions:
  ServerListPlus.Admin:
    description: Allows you to access the ServerListPlus commands.
    default: op
commands:
  serverlistplus:
    description: "${project.description}"
    aliases: [serverlist, slp]
    permission: ServerListPlus.Admin