#        _____                     __    _     _   _____ _
#       |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#       |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#       |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
#
#  @Name@ - @Description@
#  Copyright (C) 2014, @Author@
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------
main: @PluginClass@

name: @Name@
version: '@Version@'
description: "@Description@"

author: '@Author@'
website: '@Website@'

depend: [ProtocolLib]

permissions:
  ServerListPlus.Admin:
    description: Allows you to access the ServerListPlus commands.
    default: op
commands:
  serverlistplus:
    description: "@Description@"
    aliases:
      - 'serverlist+'
      - 'serverlist'
      - 'slp'
      - 'sl+'
      - 's++'
      - 'serverping+'
      - 'serverping'
      - 'spp'
    permission: ServerListPlus.Admin