main: @PluginClass@

name: @Name@
version: '@Version@'
description: "@Description@"

author: '@Author@'
website: '@Website@'

depend: [ProtocolLib]

permissions:
  serverlistplus.admin:
    description: Allows you to access the ServerListPlus commands.
    default: op
commands:
  serverlistplus:
    description: "@Description@"
    aliases:
      - 'serverlist+'
      - 'serverlist'
      - 'slp'
      - 'sl+'
      - 's++'
      - 'serverping+'
      - 'serverping'
      - 'spp'
      - 'slus'
    permission: serverlistplus.admin